import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.scss";
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });
import AuthHeader from "@/components/auth/authHeader";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider enableSystem={false}>
                    <AuthHeader />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
